### Send a test message to the REST API
POST http://localhost:8200/api/v1/messages
Content-Type: application/json

{
  "senderId": 1,
  "toUserId": 2,
  "text": "Hello, this is a test message, I am ruibin",
  "timestamp": 1623677767000,
  "read": false
}

### Test Elasticsearch
POST http://localhost:8700/logs
Content-Type: application/json

{
  "service": "message-service",
  "level": "INFO",
  "message": "Hello, this is a test message, I am ruibin"
}


### Creaet a user
POST http://localhost:8100/api/v1/users
Content-Type: application/json

{
  "password": "ruibin",
  "email": "ruibin.zhang@gmaidldd.com"
}

