debug: false
spring:
  application:
    name: messages
  cloud:
    config:
      name: messages, services
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

