debug: false
spring:
  application:
    name: messages
  cloud:
    config:
      name: messages, services
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
