eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8300
spring:
  application:
    name: locks
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/locks
    username: ruibin
    password: ruibin123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    users-url: http://localhost:8222/api/v1/users

management:
  tracing:
    sampling:
      probability: 1.0
